version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Logging into DockerHub
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - CWD=$(pwd)
  build:
    commands:
      - echo Build started on `date`
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "IMAGE_TAG=$IMAGE_TAG"
      - echo "Building docker image"
      - docker build -t "$IMAGE_NAME:$IMAGE_TAG" --build-arg IMAGE_TAG=$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo "Pushing the Docker image"
      - docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_REPO_URL
      - docker push "${IMAGE_REPO_URL}:${IMAGE_TAG}"
      - echo "TODO update task definition"
