version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo Logging into DockerHub
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - CWD=$(pwd)
  build:
    commands:
      - echo Build started on `date`
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "IMAGE_TAG=$IMAGE_TAG"
      - echo "Building docker image"
      - docker build -t "$IMAGE_NAME:$IMAGE_TAG" --build-arg IMAGE_TAG=$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo "Pushing the Docker image"
      - docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_REPO_URL:$IMAGE_TAG
      - docker push "${IMAGE_REPO_URL}:${IMAGE_TAG}"
      - echo "Updating task definition"
      - |
        OLD_TASK_DEFINITION=$(aws ecs describe-task-definition \
        --task-definition $TASK_DEFINITION_FAMILY | jq '.taskDefinition')
      - echo "OLD_TASK_DEFINITION=$OLD_TASK_DEFINITION"
      - IMAGE_URI="${IMAGE_REPO_URL}:${IMAGE_TAG}"
      - echo "IMAGE_URI=$IMAGE_URI"
      - |
        NEW_TASK_DEFINITION=$(echo $OLD_TASK_DEFINITION | \
        jq -r '.containerDefinitions[0].image='\"${IMAGE_URI}\" | \
        jq 'del(.taskDefinitionArn)' | \
        jq 'del(.revision)' | \
        jq 'del(.status)' | \
        jq 'del(.requiresAttributes)' | \
        jq 'del(.compatibilities)' | \
        jq 'del(.registeredAt)' | \
        jq 'del(.registeredBy)')
      - echo "NEW_TASK_DEFINITION=$NEW_TASK_DEFINITION"
      - aws ecs register-task-definition --family $TASK_DEFINITION_FAMILY --cli-input-json "$NEW_TASK_DEFINITION"
